export const cardData = [
  { level: 1, word: "Battery", id: 1 },
  { level: 1, word: "Japan", id: 2 },
  { level: 1, word: "Giraffe", id: 3 },
  { level: 1, word: "Hot Dog", id: 4 },
  { level: 1, word: "Coffee", id: 5 },
  { level: 1, word: "Pens", id: 6 },
  { level: 1, word: "Laptop", id: 7 },
  { level: 1, word: "ToothPaste", id: 8 },
  { level: 1, word: "Blood", id: 9 },
  { level: 1, word: "Piano", id: 10 },
  { level: 2, word: "Bat", id: 11 },
  { level: 2, word: "X-ray", id: 12 },
  { level: 2, word: "Time Machine", id: 13 },
  { level: 2, word: "Ghost", id: 14 },
  { level: 2, word: "Printer", id: 15 },
  { level: 2, word: "Job", id: 16 },
  { level: 2, word: "Vampire", id: 17 },
  { level: 2, word: "Uncle", id: 18 },
  { level: 2, word: "Rain forest", id: 19 },
  { level: 2, word: "Blood", id: 20 },
  { level: 3, word: "Stress", id: 21 },
  { level: 3, word: "Worries", id: 22 },
  { level: 3, word: "Part-time", id: 23 },
  { level: 3, word: "Vacation", id: 24 },
  { level: 3, word: "Trick-or-treat", id: 25 },
  { level: 3, word: "Career", id: 26 },
  { level: 3, word: "AI", id: 27 },
  { level: 3, word: "Tired", id: 28 },
  { level: 3, word: "Caleb", id: 29 },
  { level: 3, word: "Scrum", id: 30 },
];
